import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import Menu from "@/components/Menu";


const ubuntu = Ubuntu({
  weight: ["300","400", "500", "700"],
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Multi Form",
  description: "Generated by create next app",
  icons: "/favicon.png"
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>
          <main className="w-full h-screen">
            <Menu/>
            <form className="bg-white">
              {children}
            </form>
          </main>
      </body>
    </html>
  );
}
